version: "3.8"

services:
  video:
    build: .
    container_name: video-service
    ports:
      - "3002:3002"
    environment:
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:6.2
    container_name: redis-video
    networks:
      - backend

networks:
  backend:
