name: CI/CD Pipeline

# ===========================
# Author: Jesse GÃ¼nzl
# Matrikelnummer: 2577166
# ===========================

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21" # Use the node version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Create env file
        run: |
          touch .env
          echo PORT=3002 >> .env
          echo JWT_SECRET=your-secret-key123123 >> .env

      - name: Run tests
        run: npm test

  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ghcr.io/mingleflix/video-service:${{ github.sha }} .

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/mingleflix/video-service:${{ github.sha }}

  #  Using simple kubectl commands
  #  deploy:
  #    needs: build-and-push
  #    runs-on: self-hosted
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v2
  #
  #      - name: Replace image tag in Kubernetes deployment
  #        run: |
  #          export GITHUB_SHA=${GITHUB_SHA}
  #          envsubst < k8s/deployment.yaml.template > ./path/to/deployment.yaml
  #
  #      - name: Deploy to K3s
  #        run: export KUBECONFIG=~/.kube/config && kubectl apply -f k8s/

  # Using Helm
  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          helm dependency update ./helm/video-service
      - name: Deploy to Kubernetes using Helm
        run: |
          helm upgrade --install video-service ./helm/video-service \
          --values ./helm/video-service/values.yaml \
          --set image.tag=${{ github.sha }} \
          --set env.REDIS_HOST=room-management-redis-master \
          --set env.PORT=3002 \
          --namespace default
